// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbnpnjyhmxmcurffmcom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxibnBuanlobXhtY3VyZmZtY29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTk5NjEsImV4cCI6MjA2OTU3NTk2MX0.ZxaOF-fdk3orrvqCCR8qdLmDEcv81FlmCM1XRQ3Odg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});